parameters:
#    tdm_swift_mailer_event.example.class: TDM\SwiftMailerEventBundle\Example

services:
#    tdm_swift_mailer_event.example:
#        class: %tdm_swift_mailer_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
